### ISSUE TITLE
Fix embroider-optimized build

### ISSUE THREAD

**Issue by elwayman02** [sukima/ember-validity-modifier#20]
embroider-optimized is currently not supported by this package, so the failures in our experimental CI build will need to be fixed before it can be declared fully embroider compatible.

**Comment by elwayman02** [comment]
More info: https://linkedin.ghe.com/multiproduct/ember-cli-pemberly-node-console/pull/263

**Comment by sukima** [comment]
Got a hint that the reason for the failure is that my tests add helpers by using `this.owner.register()` and that instead we should reference the helpers off the `this.` context.

Instead of `{{test-helper}}` in the `render(hbs)` we do `{{this.testHelper}}` assigning it with

```js
this.set('testHelper', helper(....));
```

I will try this out over the weekend.
